version: '3.7'

services:
  fast-dev-stack:
    container_name: fast-dev
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    image: "lensesio/fast-data-dev:latest"
    environment:
      ADV_HOST: fast-dev

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis-service:
      container_name: redis
      ports:
        - 6379:6379
      image: "redis:alpine"

  haproxy:
    image: haproxy:2.1.3
    volumes:
        - ./haproxy:/haproxy-override
        - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
        - falcon-task-1
        - falcon-task-2
        - falcon-task-3
    ports:
        - "80:80"

  # for ease of showcase three instances like that to load balance with the HAProxy
  falcon-task-1:
    container_name: falcon-task-1
    image: falcon/falcon-task
    restart: always
    depends_on:
      - fast-dev-stack
      - rabbitmq
    expose:
     - 8090
    environment:
      SPRING_PROFILES_ACTIVE: prod

  falcon-task-2:
    container_name: falcon-task-2
    image: falcon/falcon-task
    restart: always
    depends_on:
      - fast-dev-stack
      - rabbitmq
    expose:
      - 8090
    environment:
      SPRING_PROFILES_ACTIVE: prod

  falcon-task-3:
    container_name: falcon-task-3
    image: falcon/falcon-task
    restart: always
    depends_on:
      - fast-dev-stack
      - rabbitmq
    expose:
      - 8090
    environment:
      SPRING_PROFILES_ACTIVE: prod

  rabbitmq:
    container_name: rabbitmq-stomp
    image: jorgeacetozi/rabbitmq-stomp:3.6
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
