version: '3.7'

services:
  fast-dev-stack:
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    image: "lensesio/fast-data-dev:latest"
    environment:
      ADV_HOST: 127.0.0.1

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis-service:
      ports:
        - 6379:6379
      image: "redis:alpine"