server:
  port: 8090

relay:
  host: localhost

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  kafka:
    producer:
      acks: 1
      client-id: message-service
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: 127.0.0.1:9092
    bootstrap-servers: 127.0.0.1:9092
  redis:
    host: localhost
    port: 6379
---
relay:
  host: rabbitmq

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
  kafka:
    consumer:
      bootstrap-servers: fast-dev:9092
    producer:
      bootstrap-servers: fast-dev:9092
    bootstrap-servers: fast-dev:9092
  redis:
    host: redis
    port: 6379