server:
  port: 8091

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      client-id: message-service
      group-id: falcon-task
      enable-auto-commit: true
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      acks: 1
      client-id: message-service
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: 127.0.0.1:9092
    bootstrap-servers: 127.0.0.1:9092
  redis:
    host: localhost
    port: 6379
